steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','${_LOCATION}/udemy-cicd-course/${_IAMGE}','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','${_LOCATION}/udemy-cicd-course/$_{IAMGE']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'pyflaskapp'
  - '--image'
  - '${_LOCATION}/udemy-cicd-course/${_IAMGE}'
  - '--region'
  - 'northamerica-northeast2'
  - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IAMGE: pyapprepoapp-artifact/pyappimage:latest
  _LOCATION: northamerica-northeast2-docker.pkg.dev

