steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','northamerica-northeast2-docker.pkg.dev/gcp-cicd-demo-409307/pyapprepoapp-artifact/pyappimage:latest','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','northamerica-northeast2-docker.pkg.dev/gcp-cicd-demo-409307/pyapprepoapp-artifact/pyappimage:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'pyflaskapp'
  - '--image'
  - 'northamerica-northeast2-docker.pkg.dev/gcp-cicd-demo-409307/pyapprepoapp-artifact/pyappimage:latest'
  - '--region'
  - 'northamerica-northeast2'
  - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
