steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','${_LOCATION}/${_PROJECT}/${_IMAGE}','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','${_LOCATION}/${_PROJECT}/${_IMAGE}']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'pyflaskapp'
  - '--image'
  - '${_LOCATION}/${_PROJECT}/${_IMAGE}'
  - '--region'
  - 'northamerica-northeast2'
  - '--allow-unauthenticated'
ß
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: pyapprepoapp-artifact/pyappimage:latest
  _LOCATION: northamerica-northeast2-docker.pkg.dev
  _PROJECT: udemy-cicd-course
