######### COMPLETE EXAMPLE 1  #########

steps:
  - name: "bash"
    script: |
      #!/usr/bin/env bash
      echo "Hello World"
  - name: "python"
    script: |
      #!/usr/bin/env python
      print('Hello World from Python')


######### COMPLETE EXAMPLE 2  #########

steps:
  - name: "bash"
    script: |
      #!/usr/bin/env bash
      echo "Hello World" > dummy.txt
      echo "Hello World again" >> dummy.txt
      echo "Opening dummy.txt"
      cat dummy.txt


options:
  logging: CLOUD_LOGGING_ONLY