steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -x
      echo "Logging in as $Docker-User"
      docker login --username "$Docker-User" --password "$Docker-Password"


- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t $$Docker-User/pyappimage:latest .']
  secretEnv: ['Docker-User']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push $$Docker-User/pyappimage:latest']
  secretEnv: ['Docker-User']

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/Docker-User/versions/3
    env: 'Docker-User'
  - versionName: projects/${PROJECT_ID}/secrets/Docker-Password/versions/2
    env: 'Docker-Password'


options:
  logging: CLOUD_LOGGING_ONLY