steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$DOCKER_USERNAME --password=$$DOCKER_PASSWORD']
  secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t $$DOCKER_USERNAME/pyappimage:latest .']
  secretEnv: ['DOCKER_USERNAME']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push $$DOCKER_USERNAME/pyappimage:latest']
  secretEnv: ['DOCKER_USERNAME']

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/dockerUser/versions/1
    env: 'DOCKER_USERNAME'
  - versionName: projects/${PROJECT_ID}/secrets/dockerPassword/versions/2
    env: 'DOCKER_PASSWORD'


options:
  logging: CLOUD_LOGGING_ONLY