steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      set -x
      echo "Logging in as $dockerUser"
      docker login --username "$dockerUser" --password "$dockerPassword"


- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t $$dockerUser/pyappimage:latest .']
  secretEnv: ['dockerUser']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push $$dockerUser/pyappimage:latest']
  secretEnv: ['dockerUser']

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/dockerUser/versions/1
    env: 'dockerUser'
  - versionName: projects/${PROJECT_ID}/secrets/dockerPassword/versions/1
    env: 'dockerPassword'


options:
  logging: CLOUD_LOGGING_ONLY